### ISSUE TITLE
Add "progress" and "answers" sections to questionnaire templates

### ISSUE THREAD

**Issue by sinclairs** [CriminalInjuriesCompensationAuthority/q-template-generator#3]
Currently [q-router](https://github.com/CriminalInjuriesCompensationAuthority/q-router/blob/master/lib/index.js) adds these when initialising the questionnaire. This is not q-router's responsibility.

They should be set as follows:

```json
"answers": {},
"progress": ["value of routes.initial"]
```

**Comment by armoj** [comment]
Created Pull Request #4 to resolve this issue

**Comment by armoj** [comment]
Will the `q-router` need to be updated in relation to this issue?

namely this section of `index.js`:

```js
function qRouter(spec) {
    const q = Object.assign({}, spec);
    const fsm = createMachine(q.routes);
    q.answers = q.answers || {}; // <---------------------------------- this line? (LINE: 7)
    q.progress = q.progress || [fsm.initialState.value]; // <---------- and this line? (LINE: 8)
    q.current = q.current || {
        id: fsm.initialState.value,
        context: q
    };
...
````

Given that the `answers`, and `progress` properties are defined in the `q-template-generator` (as a result of this issue), I am assuming that we don't need to explicitly set them again. Is this thinking correct?

**Comment by sinclairs** [comment]
Yeah, it'll only set them if they don't exist, however given #4 has been merged, q-router should throw an error.

**Comment by BarryPiccinni** [comment]
Should the initial state be pushed into the progress array here? I don't feel it reads right having the progress set on a fresh template that hasn't been touched by a user yet.

Also, I assume this will need to be added to by the logic that currently resides in cica-web. Would it not make sense to push the sectionId into the array on POST? Just thinking ahead - If it's done this way I'd need to add some logic in to push the ID except the initial one.
